In [ ]:
import requests
import pandas as pd
import time
from dotenv import load_dotenv
import os

In [ ]:
load_dotenv()
tmdb_api_key = os.getenv("TMDB_API_KEY")
if tmdb_api_key:
    print("tmdb Key loaded!")
else:
    print("ERROR: Key not found. Check your '.env' file.")

tmdb Key loaded!

In [ ]:
load_dotenv()
omdb_api_key = os.getenv("OMDB_API_KEY")
if omdb_api_key:
    print("omdb Key loaded!")
else:
    print("ERROR: Key not found. Check your '.env' file.")

omdb Key loaded!

In [ ]:
def fetch_tmdb_movie_details(movie_id, api_key):
    url = f"https://api.themoviedb.org/3/movie/{movie_id}"

    params = {
        "api_key": api_key
    }

    response = requests.get(url, params=params)

    if response.status_code != 200:
        return {}

    return response.json()

In [ ]:
def fetch_omdb_data(imdb_id, omdb_api_key):

    if not imdb_id:
        return {}

    url = "http://www.omdbapi.com/"

    params = {
        "apikey": omdb_api_key,
        "i": imdb_id
    }

    response = requests.get(url, params=params)

    if response.status_code != 200:
        return {}

    return response.json()

In [ ]:
def fetch_tmdb_genre_mapping(api_key):
    """Fetch genre mapping from TMDb API."""
    url = "https://api.themoviedb.org/3/genre/movie/list"
    params = {"api_key": api_key}
    response = requests.get(url, params=params)
    data = response.json()

    return {genre["id"]: genre["name"] for genre in data.get("genres", [])}

In [ ]:
def fetch_tmdb_movies(tmdb_api_key,omdb_api_key,num_pages=50):
    """Fetch movies data from TMDb with a delay between requests."""
    movie_list = []
    genre_mapping = fetch_tmdb_genre_mapping(tmdb_api_key)
    base_url = "https://api.themoviedb.org/3/discover/movie"

    for page in range(1, num_pages + 1):
        print(f"Processing page {page}/{num_pages}")
        params = {
            "api_key": tmdb_api_key,
            "sort_by": "popularity.desc",
            "page": page
            }
        response = requests.get(base_url, params=params)
        data = response.json()

        for movie in data.get("results", []):

            release_date = movie.get("release_date")
            year = release_date[:4] if release_date else "Unknown"

            genre_names = [
                genre_mapping.get(genre_id, "Unknown")
                for genre_id in movie.get("genre_ids", [])
                ]

            movie_id = movie.get("id")

            details = fetch_tmdb_movie_details(
                movie_id,
                tmdb_api_key
                )

            imdb_id = details.get("imdb_id")

            omdb_data = fetch_omdb_data(
                imdb_id,
                omdb_api_key
                )
            if omdb_data.get("Response") == "False":
                omdb_data = {}

            movie_list.append({

                "TMDb_ID": movie_id,
                "IMDb_ID": imdb_id,

                "Title": movie.get("title"),
                "Year": year,

                "Genre": ", ".join(genre_names),
                "Primary Genre": genre_names[0] if genre_names else None,

                "TMDb Rating": movie.get("vote_average"),
                "TMDb Votes": movie.get("vote_count"),
                "Popularity": movie.get("popularity"),

                "Revenue": details.get("revenue"),
                "Budget": details.get("budget"),
                "Runtime": details.get("runtime"),

                "IMDb Rating": omdb_data.get("imdbRating"),
                "IMDb Votes": omdb_data.get("imdbVotes"),
                "Box Office": omdb_data.get("BoxOffice")
            })

            time.sleep(0.2)  # avoid hammering APIs

    return pd.DataFrame(movie_list)

In [ ]:
sample_movies_df = fetch_tmdb_movies(
    tmdb_api_key,
    omdb_api_key,
    num_pages=1
)

print(len(sample_movies_df))
sample_movies_df.head()

Processing page 1/1
20

,TMDb_ID,IMDb_ID,Title,Year,Genre,Primary Genre,TMDb Rating,TMDb Votes,Popularity,Revenue,Budget,Runtime,IMDb Rating,IMDb Votes,Box Office
0,1339713,tt37287335,Obsession,2026,"Horror, Thriller",Horror,7.917,841,581.7554,297445815,750000,108,8.2,"50,183","$104,757,650"
1,931285,tt17490712,Mortal Kombat II,2026,"Action, Fantasy, Adventure",Action,7.988,1449,519.4298,128857238,80000000,116,6.7,"36,627","$77,767,462"
2,936075,tt11378946,Michael,2026,"Music, Drama",Music,8.653,2635,503.0910,934009960,250000000,128,7.7,"107,813","$340,068,767"
3,1367220,tt33988385,Karuppu,2026,"Action, Fantasy",Action,7.059,17,384.3573,3345079,16000000,152,N/A,N/A,N/A
4,879945,tt16288638,The Unknown Man,2021,Drama,Drama,7.800,9,325.1904,0,0,23,7.0,53,N/A

In [ ]:
movies_df = fetch_tmdb_movies(
    tmdb_api_key,
    omdb_api_key,
    num_pages=50
)

print(len(movies_df))
movies_df.head()

Processing page 1/50
Processing page 2/50
Processing page 3/50
Processing page 4/50
Processing page 5/50
Processing page 6/50
Processing page 7/50
Processing page 8/50
Processing page 9/50
Processing page 10/50
Processing page 11/50
Processing page 12/50
Processing page 13/50
Processing page 14/50
Processing page 15/50
Processing page 16/50
Processing page 17/50
Processing page 18/50
Processing page 19/50
Processing page 20/50
Processing page 21/50
Processing page 22/50
Processing page 23/50
Processing page 24/50
Processing page 25/50
Processing page 26/50
Processing page 27/50
Processing page 28/50
Processing page 29/50
Processing page 30/50
Processing page 31/50
Processing page 32/50
Processing page 33/50
Processing page 34/50
Processing page 35/50
Processing page 36/50
Processing page 37/50
Processing page 38/50
Processing page 39/50
Processing page 40/50
Processing page 41/50
Processing page 42/50
Processing page 43/50
Processing page 44/50
Processing page 45/50
Processing page 46/50
Processing page 47/50
Processing page 48/50
Processing page 49/50
Processing page 50/50
1000

,TMDb_ID,IMDb_ID,Title,Year,Genre,Primary Genre,TMDb Rating,TMDb Votes,Popularity,Revenue,Budget,Runtime,IMDb Rating,IMDb Votes,Box Office
0,1339713,tt37287335,Obsession,2026,"Horror, Thriller",Horror,7.917,841,581.7554,297445815,750000,108,8.2,"50,183","$104,757,650"
1,931285,tt17490712,Mortal Kombat II,2026,"Action, Fantasy, Adventure",Action,7.988,1449,519.4298,128857238,80000000,116,6.7,"36,627","$77,767,462"
2,936075,tt11378946,Michael,2026,"Music, Drama",Music,8.653,2635,503.0910,934009960,250000000,128,7.7,"107,813","$340,068,767"
3,1367220,tt33988385,Karuppu,2026,"Action, Fantasy",Action,7.059,17,384.3573,3345079,16000000,152,N/A,N/A,N/A
4,879945,tt16288638,The Unknown Man,2021,Drama,Drama,7.800,9,325.1904,0,0,23,7.0,53,N/A

In [ ]:
movies_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   TMDb_ID        1000 non-null   int64
 1   IMDb_ID        978 non-null    str
 2   Title          1000 non-null   str
 3   Year           1000 non-null   str
 4   Genre          1000 non-null   str
 5   Primary Genre  993 non-null    str
 6   TMDb Rating    1000 non-null   float64
 7   TMDb Votes     1000 non-null   int64
 8   Popularity     1000 non-null   float64
 9   Revenue        1000 non-null   int64
 10  Budget         1000 non-null   int64
 11  Runtime        1000 non-null   int64
 12  IMDb Rating    963 non-null    str
 13  IMDb Votes     963 non-null    str
 14  Box Office     963 non-null    str
dtypes: float64(2), int64(5), str(8)
memory usage: 190.9 KB

In [ ]:
movies_df.to_csv("movies_data.csv", index=False)