In [1]:
import pandas as pd
import numpy as np

In [2]:
df_dataset = pd.read_csv('movies_data.csv')
df_dataset.head()

,TMDb_ID,IMDb_ID,Title,Year,Genre,Primary Genre,TMDb Rating,TMDb Votes,Popularity,Revenue,Budget,Runtime,IMDb Rating,IMDb Votes,Box Office
0,1339713,tt37287335,Obsession,2026,"Horror, Thriller",Horror,7.917,841,581.7554,297445815,750000,108,8.2,"50,183","$104,757,650"
1,931285,tt17490712,Mortal Kombat II,2026,"Action, Fantasy, Adventure",Action,7.988,1449,519.4298,128857238,80000000,116,6.7,"36,627","$77,767,462"
2,936075,tt11378946,Michael,2026,"Music, Drama",Music,8.653,2635,503.0910,934009960,250000000,128,7.7,"107,813","$340,068,767"
3,1367220,tt33988385,Karuppu,2026,"Action, Fantasy",Action,7.059,17,384.3573,3345079,16000000,152,NaN,NaN,NaN
4,879945,tt16288638,The Unknown Man,2021,Drama,Drama,7.800,9,325.1904,0,0,23,7.0,53,NaN

In [3]:
df_dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   TMDb_ID        1000 non-null   int64
 1   IMDb_ID        978 non-null    str
 2   Title          1000 non-null   str
 3   Year           1000 non-null   str
 4   Genre          993 non-null    str
 5   Primary Genre  993 non-null    str
 6   TMDb Rating    1000 non-null   float64
 7   TMDb Votes     1000 non-null   int64
 8   Popularity     1000 non-null   float64
 9   Revenue        1000 non-null   int64
 10  Budget         1000 non-null   int64
 11  Runtime        1000 non-null   int64
 12  IMDb Rating    841 non-null    float64
 13  IMDb Votes     857 non-null    str
 14  Box Office     611 non-null    str
dtypes: float64(3), int64(5), str(7)
memory usage: 186.7 KB

In [6]:
df_dataset['Year'] = pd.to_numeric(df_dataset['Year'], errors='coerce')
df_dataset['Box Office'] = df_dataset['Box Office'].replace('[\$,]', '', regex=True).astype(float)
df_dataset.head()

,TMDb_ID,IMDb_ID,Title,Year,Genre,Primary Genre,TMDb Rating,TMDb Votes,Popularity,Revenue,Budget,Runtime,IMDb Rating,IMDb Votes,Box Office
0,1339713,tt37287335,Obsession,2026.0,"Horror, Thriller",Horror,7.917,841,581.7554,297445815,750000,108,8.2,"50,183",104757650.0
1,931285,tt17490712,Mortal Kombat II,2026.0,"Action, Fantasy, Adventure",Action,7.988,1449,519.4298,128857238,80000000,116,6.7,"36,627",77767462.0
2,936075,tt11378946,Michael,2026.0,"Music, Drama",Music,8.653,2635,503.0910,934009960,250000000,128,7.7,"107,813",340068767.0
3,1367220,tt33988385,Karuppu,2026.0,"Action, Fantasy",Action,7.059,17,384.3573,3345079,16000000,152,NaN,NaN,NaN
4,879945,tt16288638,The Unknown Man,2021.0,Drama,Drama,7.800,9,325.1904,0,0,23,7.0,53,NaN

In [7]:
missing = df_dataset.isna().sum()

missing_pct = (
    df_dataset.isna().mean() * 100
).round(2)

pd.DataFrame({
    "Missing Count": missing,
    "Missing %": missing_pct
}).sort_values("Missing %", ascending=False)

               Missing Count  Missing %
Box Office               389       38.9
IMDb Rating              159       15.9
IMDb Votes               143       14.3
IMDb_ID                   22        2.2
Primary Genre              7        0.7
Genre                      7        0.7
Year                       3        0.3
TMDb Rating                0        0.0
Title                      0        0.0
TMDb_ID                    0        0.0
TMDb Votes                 0        0.0
Budget                     0        0.0
Revenue                    0        0.0
Popularity                 0        0.0
Runtime                    0        0.0

In [8]:
df_dataset = df_dataset.dropna(
    subset=[
        "IMDb_ID",
        "Primary Genre",
        "Genre",
        "Year"
    ]
)

In [9]:
df_dataset["IMDb Votes"] = (
    df_dataset["IMDb Votes"]
      .astype(str)
      .str.replace(",", "", regex=False)
)

df_dataset["IMDb Votes"] = pd.to_numeric(
    df_dataset["IMDb Votes"],
    errors="coerce"
)

In [10]:
print("Revenue = 0:", (df_dataset["Revenue"] == 0).sum())
print("Budget = 0:", (df_dataset["Budget"] == 0).sum())

Revenue = 0: 300
Budget = 0: 307

In [11]:
df_dataset["Revenue"] = df_dataset["Revenue"].replace(0, np.nan)
df_dataset["Budget"] = df_dataset["Budget"].replace(0, np.nan)

In [12]:
df_dataset[["Revenue", "Budget"]].isna().sum()

Revenue    300
Budget     307
dtype: int64

In [13]:
current_year = 2026
start_year = current_year - 26

df_dataset_last_26_years_clean = df_dataset.loc[(df_dataset["Year"] >= start_year) & (df_dataset["Year"] <= current_year)].copy()

df_dataset_last_26_years_clean["Year"] = df_dataset_last_26_years_clean["Year"].astype(int)

print(f"Year Range       : {start_year} to {current_year}")
print(f"Total Records     : {len(df_dataset)}")
print(f"Filtered Records  : {len(df_dataset_last_26_years_clean)}")
df_dataset_last_26_years_clean.head()

Year Range       : 2000 to 2026
Total Records     : 974
Filtered Records  : 815

,TMDb_ID,IMDb_ID,Title,Year,Genre,Primary Genre,TMDb Rating,TMDb Votes,Popularity,Revenue,Budget,Runtime,IMDb Rating,IMDb Votes,Box Office
0,1339713,tt37287335,Obsession,2026,"Horror, Thriller",Horror,7.917,841,581.7554,297445815.0,750000.0,108,8.2,50183.0,104757650.0
1,931285,tt17490712,Mortal Kombat II,2026,"Action, Fantasy, Adventure",Action,7.988,1449,519.4298,128857238.0,80000000.0,116,6.7,36627.0,77767462.0
2,936075,tt11378946,Michael,2026,"Music, Drama",Music,8.653,2635,503.0910,934009960.0,250000000.0,128,7.7,107813.0,340068767.0
3,1367220,tt33988385,Karuppu,2026,"Action, Fantasy",Action,7.059,17,384.3573,3345079.0,16000000.0,152,NaN,NaN,NaN
4,879945,tt16288638,The Unknown Man,2021,Drama,Drama,7.800,9,325.1904,NaN,NaN,23,7.0,53.0,NaN

In [ ]:
df_dataset_last_26_years_clean.to_csv("data_movies_cleaned.csv", index=False)